export const defaultFrota = [];
export const defaultCarretas = [];
export const defaultAgregados = [];

export const templates = {
  frota: {
    identificador: "",
    placa: "",
    idTecnologia: "",
    dataTeste: "",
    teclado: "",
    sirene: "",
    deseng: "",
    trava: "",
    sensorBau: "",
    portaCarona: "",
    portaMotorista: "",
    bloqueio: "",
    panico: "",
    violacao: "",
    aprovado: "",
    usuario: "",
    motorista: "",
    contato: "",
  },
  carretas: {
    placa: "",
    carroceria: "",
    venc: 60,
    dataTeste: "",
    testeOk: "",
    travaBau: "",
    sensorBau: "",
    aprovado: "",
    usuario: "",
    observacoes: "",
  },
  agregados: {
    identificador: "",
    placa: "",
    idTecnologia: "",
    dataTeste: "",
    teclado: "",
    sirene: "",
    deseng: "",
    trava: "",
    sensorBau: "",
    portaCarona: "",
    portaMotorista: "",
    bloqueio: "",
    panico: "",
    violacao: "",
    aprovado: "",
    usuario: "",
    motorista: "",
    contato: "",
  },
};

export const fieldLabels = {
  identificador: "Identificador",
  placa: "Placas",
  idTecnologia: "ID Tecnologia",
  dataTeste: "Data Teste",
  teclado: "Teclado",
  sirene: "Sirene",
  deseng: "Deseng.",
  trava: "Trava",
  sensorBau: "Sensor Baú",
  portaCarona: "Porta Carona",
  portaMotorista: "Porta Motorista",
  bloqueio: "Bloqueio",
  panico: "Pânico",
  violacao: "Violação",
  aprovado: "Aprovado/Reprovado",
  usuario: "Usuário",
  motorista: "Motorista",
  contato: "Contato",
  carroceria: "Carroceria",
  venc: "Venc. (dias)",
  testeOk: "Teste OK",
  travaBau: "Trava de Baú",
  observacoes: "Observações",
};
